#!/bin/bash

# Script automatically executed when "composer (update|remove|require)" is run

# Git hooks (can be deleted when doing a mirror clone) -- option u copies only if destination is different from source

cp -uv ./scripts/git-hooks/pre-commit ./.git/hooks/

# Gitub hooks (can be deleted when doing a mirror clone)

mkdir -p ./.github
cp -uvr ./scripts/github/** ./.github/
