#!/bin/bash

# Script automatically executed when "composer (update|remove|require)" is run

# Execute only in local install, not on github
# Not local, exit normaly
if [ ! -d "./../svn" ];then
	echo "Not a local install, exit"
	exit 0
fi

# Update main composer
echo 'updating composer in src folder...'
cd ./src && composer update
