name: "PHPStan and Phan"
on:
  push:
    branches: "*"
  pull_request:
permissions: read-all
env:
  cache-version: 1
jobs:
   standard:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1', '8.2', '8.3', '8.4']
    env:
      php-extensions: ast
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup PHP extension caching"
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php-extensions }}
          key: php-extensions-${{ runner.os }}-foov4-${{ env.cache-version }}

      - name: "Cache extensions"
        uses: actions/cache@v5
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}-foov4
          restore-keys: ${{ steps.extcache.outputs.key }}-foov4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php-extensions }}
          coverage: none

      - name: "Cache Composer dependencies"
        id: composer-dependencies
        uses: actions/cache@v4
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-
            composer-dependencies-${{ runner.os }}-

      - name: "Install Composer dependencies"
        run: |
          composer install -n --prefer-dist --ignore-platform-reqs
          cd src
          composer install -n --prefer-dist
          composer update --no-dev --no-scripts --optimize-autoloader

      - name: "Code analyser"
        run: |
          composer run-script static-code-analyser
