# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# https://github.com/WordPress/plugin-check-action/

name: 'WP plugin check'
permissions: read-all
env:
  cache-version: 1
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ wp_plugin_check ]
  push:
    branches: "*"
  pull_request:
jobs:
  standard:
    runs-on: ${{ matrix.operating-system }}
    # Prevents dependabot to run the check, which always fails
#    if: ${{ github.actor != 'dependabot[bot]' }} # now it works, keeping it for the records
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
    env:
      php-extensions: ast
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Setup PHP extension caching
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php-extensions }}
          key: php-extensions-${{ runner.os }}-foov4-${{ env.cache-version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php-extensions }}
          coverage: none

      - name: Cache Composer dependencies
        id: composer-dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-${{ hashFiles('composer.lock') }}
            composer-dependencies-${{ runner.os }}-foov4-${{ env.cache-version }}-
            composer-dependencies-${{ runner.os }}-

      - name: Install Composer dependencies
        run: |
          composer install -n --prefer-dist
          cd src
          composer install -n --prefer-dist

      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Node.js environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo '::debug::deps npm cache miss - installing deps'
          npm install
        
      - name: Prepare Lumière folder for plugin check
        run: |
          npm run build:github
          cp -R ./dist ${{ runner.temp }}/lumiere-movies

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1.1.1
        with:
          build-dir: ${{ runner.temp }}/lumiere-movies
          exclude-directories: 'vendor,.wordpress-org'
          ignore-warnings: 'PluginCheck.CodeAnalysis.ImageFunctions.NonEnqueuedImage,WordPress.PHP.DevelopmentFunctions.error_log_wp_debug_backtrace_summary'

