# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Check Website Links"

on:
  push:
    branches: "*"
    paths:
      - '.github/workflows/check-dead-links.yml'

jobs:
  website-links:
    name: "Check for broken links"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check for broken links"
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'https://www.wordpress.org/,https://www.jcvignoli.com'
          resolve_before_filtering: 'true'
          exclude_url_prefix: 'mailto:,https://github.com/jcvignoli'
          verbose: 'warning'
          max_retry_time: 30
          max_retries: 3
