name: "CI"
on:
  push:
    branches: "*"
  pull_request:
env:
  php-version: 8.1
  cache-version: 1
jobs:
   lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      php-extensions: ast
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          coverage: none

      - name: "Install Composer dependencies"
        run: |
          composer install -n --prefer-dist

      - name: "Lint"
        run: |
          composer run-script lint
